apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: default
spec:
  global:
    clusterName: dev-cluster-1
    site: datadoghq.com
    
    credentials:
      apiSecret:
        secretName: datadog-api-key
        keyName: api-key
    
    tags:
      - env:development
      - cluster:dev-cluster-1
    
    criSocketPath: /var/run/crio/crio.sock
    
    kubelet:
      tlsVerify: false
  
  features:
    apm:
      enabled: true
      hostPortConfig:
        enabled: true
    
    logCollection:
      enabled: true
      containerCollectAll: true
    
    liveProcessCollection:
      enabled: true
    
    liveContainerCollection:
      enabled: true
    
    orchestratorExplorer:
      enabled: true
    
    npm:
      enabled: true
  
  override:
    nodeAgent:
      image:
        tag: latest
      
      tolerations:
        - operator: Exists
      
      containers:
        agent:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
    
    clusterAgent:
      image:
        tag: latest
      
      replicas: 1
      
      containers:
        cluster-agent:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi