apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
  labels:
    env: staging
    managed-by: platform-engineering
spec:
  global:
    clusterName: staging-cluster-1
    site: datadoghq.com
    
    credentials:
      apiSecret:
        secretName: datadog-api-key
        keyName: api-key
      appSecret:
        secretName: datadog-app-key
        keyName: app-key
    
    tags:
      - env:staging
      - region:primary
      - cluster:staging-cluster-1
      - platform:openshift
      - managed-by:platform-engineering
    
    criSocketPath: /var/run/crio/crio.sock
    
    kubelet:
      tlsVerify: false
  
  features:
    apm:
      enabled: true
      hostPortConfig:
        enabled: true
        port: 8126
      unixDomainSocketConfig:
        enabled: true
    
    logCollection:
      enabled: true
      containerCollectAll: false  # Selective in staging
      containerCollectUsingFiles: true
    
    liveProcessCollection:
      enabled: true
    
    liveContainerCollection:
      enabled: true
    
    orchestratorExplorer:
      enabled: true
      scrubContainers: true
    
    npm:
      enabled: true
      enableConntrack: true
    
    eventCollection:
      collectKubernetesEvents: true
  
  override:
    nodeAgent:
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      
      tolerations:
        - operator: Exists
      
      hostNetwork: true
      hostPID: true
      
      securityContext:
        runAsUser: 0
        privileged: true
      
      env:
        - name: DD_LOG_LEVEL
          value: info
        - name: DD_CONTAINER_EXCLUDE
          value: "name:datadog-agent"
        - name: DD_CONTAINER_INCLUDE
          value: "kube_namespace:^(default|staging-.*|apps-.*)$"
    
    clusterAgent:
      replicas: 2  # HA in staging
      
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      
      metricsProvider:
        enabled: true
        useDatadogMetrics: true
        wpaController: true
      
      admissionController:
        enabled: true
        mutateUnlabelled: false
      
      clusterChecksEnabled: true
      
      env:
        - name: DD_LOG_LEVEL
          value: info
    
    clusterChecksRunner:
      enabled: true
      replicas: 2
      
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
