apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog-agent-dev
  namespace: argocd
  labels:
    component: agent
    env: development
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-observability
  
  source:
    repoURL: https://github.com/your-org/datadog-operator-deployment.git  # CHANGE THIS
    targetRevision: main
    path: agents/dev
  
  destination:
    server: https://kubernetes.default.svc
    namespace: datadog
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
  
  # Sync wave: deploy after operator
  syncWaves:
    - wave: 10
