apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    clusterName: prod-cluster-1
    site: datadoghq.com
    
    credentials:
      apiSecret:
        secretName: datadog-api-key
        keyName: api-key
      appSecret:
        secretName: datadog-app-key
        keyName: app-key
    
    tags:
      - env:production
      - region:primary
      - cluster:prod-cluster-1
      - datacenter:dc1
    
    criSocketPath: /var/run/crio/crio.sock
    kubelet:
      tlsVerify: false
  
  features:
    apm:
      enabled: true
    logCollection:
      enabled: true
      containerCollectAll: false
      autoMultiLineDetection: true
    liveProcessCollection:
      enabled: true
    orchestratorExplorer:
      enabled: true
    npm:
      enabled: true
    cspm:
      enabled: true
    cws:
      enabled: true
      syscallMonitorEnabled: false
  
  override:
    nodeAgent:
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1Gi
      tolerations:
        - operator: Exists
      priorityClassName: system-node-critical
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 10%
    
    clusterAgent:
      replicas: 3
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1Gi
      metricsProvider:
        enabled: true
      admissionController:
        enabled: true
        mutateUnlabelled: false
    
    clusterChecksRunner:
      enabled: true
      replicas: 2
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi