apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-api-key
  namespace: datadog
  labels:
    app: datadog
    managed-by: platform-engineering
spec:
  refreshInterval: 1h
  
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  
  target:
    name: datadog-api-key
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        api-key: "{{ .apikey }}"
  
  data:
    - secretKey: apikey
      remoteRef:
        key: datadog/staging/api-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-app-key
  namespace: datadog
  labels:
    app: datadog
    managed-by: platform-engineering
spec:
  refreshInterval: 1h
  
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  
  target:
    name: datadog-app-key
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        app-key: "{{ .appkey }}"
  
  data:
    - secretKey: appkey
      remoteRef:
        key: datadog/staging/app-key
